---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.19.0
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4  # Use the sha / tag you want to point at
    hooks:
      - id: pylint
