name: base
channels:
  - conda-forge
dependencies:
  - python=3.9
  - boto3
  - scipy
  - rasterio
  - geopandas
  - pandas
  - click
  - shapely
  - fiona
  - xarray
  - toolz
  - pip:
      - boto3_fixtures
