name: dea-vectoriser
channels:
  - conda-forge
dependencies:
  - python=3.9
  - boto3
  - scipy
  - rasterio
  - geopandas
  - pandas
  - click
  - shapely
  - fiona
  - pip
  - xarray
  - toolz

  # Only required for testing
  - pytest
  - pytest-cov
  - moto
  - pip:
      - boto3_fixtures
