name: dea-vectoriser
channels:
  - conda-forge
dependencies:
  - python=3.9
  - boto3
  - scipy
  - rasterio
  - geopandas
  - pandas
  - pip
  - click
  - shapely
  - fiona
  - xarray
  - toolz
  - scikit-image

  # Only required for testing
  # - pytest
  # - pytest-cov
  # - moto
  # - setuptools_scm
  # - pip:
  #     - boto3_fixtures
