name: dea-vectoriser
channels:
  - conda-forge
dependencies:
  - python=3.9
  - boto3
  - scipy
  - rasterio
  - geopandas
  - pandas
  - pip
  - click
  - shapely
  - fiona
  - xarray
  - toolz
    #  - pip:
    #      - boto3_fixtures
  # Only required for testing
  #  - pytest
  #  - pytest-cov
  #  - moto
