---
# yamllint disable rule:line-length
name: Release

"on":
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Get tag for this build if it exists
      #   run: |
      #     echo "VERSION=$(cat statistician/version.txt)" >> $GITHUB_ENV
      - name: Extract Git Tag
        run: echo "DOCKER_TAG=GeoscienceAustralia/dea-vectoriser:${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.DOCKER_TAG }}

      - name: Test
        run: |
          docker run --rm ${{ env.DOCKER_TAG }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: GeoscienceAustralia/dea-vectoriser:latest,${{ env.DOCKER_TAG }}
